<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<?php $sportsHelper = $this->helper('Zanders\Sports\Helper\Data'); ?>
<?php if($sportsHelper->getCustomerGroupId()>=2){ ?>
	<div class="product alert <?= $block->getHtmlClass() ?>">
	    <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
	       title="<?= $block->escapeHtmlAttr(__($block->getSignupLabel())) ?>" class="action alert">
	        <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
	    </a>
	</div>
<?php } ?>
