<div class="footer">
	<div class="footer-top">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top_content')->toHtml(); ?>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom_content')->toHtml(); ?>
		</div>
	</div>
</div>