<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="col2-set">
    <div class="box">
        <div class="box-title">
            <h3><?= $block->escapeHtml(__('Address Book')) ?></h3>
            <?php /* <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a> */ ?>
        </div>
        <div class="box-content">
            <div class="col-1">
                <h4><?= $block->escapeHtml(__('Default Billing Address')) ?></h4>
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?><br />
                    <?php /* <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a> */ ?>
                </address>
            </div>
            <div class="col-2">
                <h4><?= $block->escapeHtml(__('Default Shipping Address')) ?></h4>
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?><br />
                    <?php /* <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a> */ ?>
                </address>
            </div>
        </div>
    </div>
</div>
</div>