<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="welcome-msg-dashboard">
    <p class="hello"><strong><?= $block->escapeHtml(__('Hello, '. $block->escapeHtml($block->getName()))).' !' ?></strong></p>
    <p><?= $block->escapeHtml(__('From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.')) ?></p>
</div>

<div class="box-account box-info">
    <div class="box-head">
            <h2><?= $block->escapeHtml(__('Account Information')) ?></h2>
        </div>

        <div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?= $block->escapeHtml(__('Contact Information')) ?></h3>
                <a href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                    <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?= $block->escapeHtml(__('Customer Info')) ?></h3>
            </div>
            <div class="box-content">
                <p>
                 <?= $block->escapeHtml(__("Customer Number: ")) ?>
                </p>
            </div>
        </div>
    </div>
</div>
