<div class="freight-policy">
     <h4>Zanders Freight Policy</h4>
     <p>Orders greater than $500.00 of shippable product will be shipped FREE FREIGHT!
Orders less than $500.00 of shippable product are subject to a $15.00 freight charge.
Orders less than $100.00 will be charged an additional $7.50 handling fee.
To qualify for free freight, orders will be shipped via carrier of Zanders choice.
If customer requests a different freight carrier, customer will be responsible for the freight charges.
F.O.B. our dock for orders to Hawaii, Alaska, Puerto Rico, Virgin Islands, Guam.
Additional charges apply for the following.</p>
<p>• COD orders<span style="padding-left:80px">• Wads</span><br/>
• Clay targets (Pick-up Only)<br/>
• Hazardous Material</p>
</div>