<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>



<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
		<div class="block block-cart">
			<div class="block-content">
				<!-- ko if: getCartParam('summary_count') -->
					<span class="no-empty">
						(
						<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
						<!-- ko i18n: 'items' --><!-- /ko -->
						)
					</span>
				<!-- /ko -->
				<!-- ko ifnot: getCartParam('summary_count') -->
					<span class="empty"><!-- ko i18n: '(0 items)' --><!-- /ko --></span>
				<!-- /ko -->
			</div>
		</div>
	</a>
	<?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
             	"triggerEvent" : "hover",
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "closeOnMouseLeave": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
</div>


<script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
</script>
<script type="text/x-magento-init">
{
	"[data-block='minicart']": {
		"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
	},
	"*": {
		"Magento_Ui/js/block-loader": "<?= $block->escapeJs(
			$block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
		) ?>"
	}
}
</script>
<script type="text/javascript">
     require(['jquery'], function($){
        $(document).ready(function(){
            $("[data-block='minicart']").on("dropdowndialogopen", (e) => {
                $(".block-minicart").hide();
                $(".block-minicart").slideDown(500);
				$(".fullscreen-blackout").addClass('active');
            });
            $("[data-block='minicart']").on("dropdowndialogclose", (e) => {
               $(".mage-dropdown-dialog").show();
               $('.block-minicart').slideUp(500);
			   $(".fullscreen-blackout").removeClass('active');
            });
        });
 });
</script>