<?php
/** @var \Zanders\WarningCode\ViewModel\WarningCode $viewModel */
$viewModel = $block->getData('viewModel');
$warningHtml = $viewModel->getWarningHtml();
?>
<?php if ($warningHtml): ?>
    <div class="warning-code">
        <p><strong><?= __('Warning') ?></strong>: <span><?= __('California Prop 65 Warning') ?></span></p>
    </div>
    <div class="warning-text" id="popup-warning-text" style="display: none">
        <img src="<?php echo $block->getViewFileUrl('Zanders_WarningCode::images/i_notice.gif'); ?>"
             alt="<?= __('Warning') ?>"/><?= $warningHtml ?>
    </div>
    <script>
        require(
            ['jquery', 'Magento_Ui/js/modal/modal'],
            function ($, modal) {
                let options = {
                    type: 'popup',
                    // title: '<?= __('Warning') ?>',
                    modalClass: 'modal-warning-code',
                    responsive: true,
                    buttons: []
                };
                let popup = modal(options, $('#popup-warning-text'));
                $(".warning-code").on('click', function () {
                    $('#popup-warning-text').modal("openModal");
                });
            }
        );
    </script>
<?php endif; ?>