	<?php

		 if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $helper = $this->helper('Zanders\Sports\Helper\Data');
        }



	?>

    <?php if ($exist) :?>

        <div class='box-collateral box-related_products'>
        <h2>Related Products</h2>
		<div class="owl-carousel">
               <!--  <ul> -->
                <?php foreach ($items as $_item): ?>
                   <!--  <li> -->
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>

                <div class="product-item">

                    <?php $allRelatedProductIds = $_item->getRelatedProductIds();     ?>
                    <?php $allupsellProductIds =  $_item->getUpSellProductIds();   ?>

                    <?php if((count($allRelatedProductIds) > 0) or (count($allupsellProductIds) > 0)) :  ?>
                    <a href="javascript:;" data-href="<?php echo $this->getUrl('related/index/replacement') ?>id/<?php echo $_item->getId() ?>" class="open-popup">
                            <img class="cross-popupicon"
                                src="<?php echo $helper->getMediaUrl().'images/related_icon.png'; ?>" />
                    </a>
                    <?php  endif?>

                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                            <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <div class="desc std">
                            <?php echo __('Item Number: ');?><span style="font-weight: bold;"><?php echo $_item->getSku(); ?></span>
                        </div>

                        <?php
                        $upc = $_item->getUpc();
                        if(!empty($upc )):
                        ?>
                        <div class="desc std">
                            <?php echo __('UPC') ?>: <span style="font-weight: bold;"><?php echo $this->escapeHtml($upc) ?></span>
                        </div>
                        <?php endif;?>

                        <?php /* @escapeNotVerified */ // $block->getProductPrice($_item) ?>



                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <!--  </li> -->
                <?php endforeach ?>
                <!-- </ul> -->
        </div>

        <div id='popup-modal' style='display:none;'>
        <div id ="customer-container">
            <div id='customcarosal'>
            <script id="customer-template" type="text/x-magento-template">
                <div  id="<%- data.id %>">
                    <li>
                        Name : <%- data.name %>
                    </li>
                    <li>
                        Salary : <%- data.salary %>
                    </li>
                    <li>
                        Location : <%- data.location %>
                    </li>
                </div>
            </script>
            </div>
        </div>
        </div>


        

      <script>
            require(["jquery","owlcarousel"],function($) {
                $(document).ready(function() {
                    $(".owl-carousel").owlCarousel({
                        navigation : true, // Show next and prev buttons
                        autoPlay: false, //Set AutoPlay to 3 seconds
                        items : 4,
                        margin : 20
                    });
                });
            });

        require(["jquery","Magento_Ui/js/modal/modal",'mage/template',
                "mage/mage","owlcarousel"],function($,modal,mageTemplate, alerts,owlcarousel)
                {
       		 
         	$(".open-popup").click(function () {'$','modal'
                var customurl = $(this).attr('data-href');
                var options = {
			        type: 'popup',
			        responsive: true,
			        innerScroll: false,
			        title: 'Modal Title',
			        modalClass: 'custom-modal',
			        buttons: [{
			 
			            class: '',
			            click: function () {
			                this.closeModal();
			                $('#popup-modal').html(" ");
			            }
			        }]
			    };

                $.ajax({
                    url: customurl,
                    type: 'POST',
                	complete: function(response) {
                        console.log(response);
                        var res = response.responseJSON.related;
                         console.log(res);
                        var responseData  = $.parseJSON(response.responseJSON);    
                        console.log(responseData);

                       // console.log(response.responseText);
                       // $html =  response.responseText;
                       // $data = $($html).find('.box-related_products');
                       // alert($data);
                       // $('#popup-modal').append($data);
                       // $('#popup-modal').modal(options).modal('openModal');
                       // alert('done');
                       // 
                       
                       $.each($.parseJSON('<?php echo $jsonCustomerData ?>'), function() {
                        
                        var progressTmpl = mageTemplate('#customer-template'),
                                  tmpl;
                        tmpl = progressTmpl({
                            data: {
                                name: this['name'],
                                salary: this['salary'],
                                location: this['location']
                            }
                        });

                        $('#customer-container').after(tmpl);
                        //  $("#customcarosal").owlCarousel({
                        //     navigation : true, // Show next and prev buttons
                        //     autoPlay: false, //Set AutoPlay to 3 seconds
                        //     items : 4,
                        //     margin : 20
                        // });
                        $('#popup-modal').modal(options).modal('openModal');

                        });
                        
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });

    		});

    </script>

 </div>   
    <?php endif; ?>

    
    